### ISSUE TITLE
Unable to run :  browserstack-cypress run --sync

### ISSUE THREAD

**Issue by captain-yossarian** [browserstack/browserstack-cypress-cli#126]
Hi,
After `browserstack-cypress run --sync` I'm receiving:
```
[3/15/2021, 4:34:03 PM] - info: Reading config from C:\Users\t628542\UBS\Dev\solutions-e2e-tests\browserstack.json
[3/15/2021, 4:34:03 PM] - info: Validating the config
[3/15/2021, 4:34:03 PM] - info: Creating tests.zip with files in .
[3/15/2021, 4:34:04 PM] - info: Uploading the tests to BrowserStack
[3/15/2021, 4:34:04 PM] - error:
{
  message: 'Client network socket disconnected before secure TLS connection was established',
  stack: 'Error: Client network socket disconnected before secure TLS connection was established\n' +
    '    at connResetException (internal/errors.js:604:14)\n' +
    '    at TLSSocket.onConnectEnd (_tls_wrap.js:1513:19)\n' +
    '    at Object.onceWrapper (events.js:417:28)\n' +
    '    at TLSSocket.emit (events.js:323:22)\n' +
    '    at endReadableNT (_stream_readable.js:1204:12)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:84:21)',
  code: 'ECONNRESET',
  path: null,
  host: 'api-cloud.browserstack.com',
  port: 443,
  localAddress: undefined
}
[3/15/2021, 4:34:04 PM] - error: Zip Upload failed.
[3/15/2021, 4:34:04 PM] - info: Deleted tests.zip successfully.
```

Could you please help me ?

**Comment by shawnlobo96** [comment]
@captain-yossarian This seems to be due to a network issue. Possibly due to SSL inspection on the proxy (if any) on your network.

Can you try to run a test while connecting to a different network?

**Comment by luisherranz** [comment]
We are also having problems and are unable to run it in either GitHub Actions and my local machine (macOS).

The error is `Internal Server Error` in both cases and then this appears in the console: 

```
[16/03/2021, 10:33:07] - info: Uploading the tests to BrowserStack
[16/03/2021, 10:33:14] - error: Internal Server Error!
[16/03/2021, 10:33:14] - error: Zip Upload failed.
[16/03/2021, 10:33:14] - info: Deleted tests.zip successfully.
[Error: ENOENT: no such file or directory, open 'log/build_results.txt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open', 
  path: 'log/build_results.txt'
}
```

I went back to version `1.7.1` because I noticed that there is a new `1.8.0` version from 4 days ago, but doesn't seem related to that.

This is the log in my machine:

```json
{
  "event_type": "cypress_cli_stats",
  "data": {
    "os": "darwin",
    "os_version": "19.6.0",
    "bstack_json_found_in_pwd": true,
    "cypress_json_found_in_pwd": true,
    "cli_version": "1.7.1",
    "cli_path": "/Users/luisherranz/.nvm/versions/node/v14.15.1/lib/node_modules",
    "npm_version": "7.6.0",
    "local_cypress_version": "Cypress package version: 6.2.1nCypress binary version: 6.2.1nElectron version: 11.1.1nBundled Node version: 12.18.3",
    "ci_environment": null,
    "event_timestamp": "16/03/2021, 10:33:15",
    "data": {
      "cypress_version": "6"
    },
    "cli_args": {
      "_": ["run"],
      "sync": true,
      "parallels": 1,
      "p": 1,
      "config-file": "./browserstack.json",
      "cf": "./browserstack.json",
      "configFile": "./browserstack.json",
      "specs": "integration/frontity-*/**/amp.spec.js,integration/frontity-*/**/amp.spec.ts",
      "s": "integration/frontity-*/**/amp.spec.js,integration/frontity-*/**/amp.spec.ts",
      "spec": "integration/frontity-*/**/amp.spec.js,integration/frontity-*/**/amp.spec.ts",
      "ccf": "./cypress.json",
      "cypress-config-file": "./cypress.json",
      "cypressConfigFile": "./cypress.json",
      "disable-npm-warning": false,
      "disableNpmWarning": false,
      "headed": false,
      "$0": "/Users/luisherranz/Code/frontity/e2e/node_modules/.bin/browserstack-cypress"
    },
    "message": "Internal Server Error!nZip Upload failed.",
    "message_type": "error",
    "error_code": "zip_upload_failed"
  }
}
```

And the same happens in GitHub actions: https://github.com/frontity/frontity/pull/749/checks?check_run_id=2120243778

**Comment by captain-yossarian** [comment]
@shawnlobo96  Hi , thanks for response.
You are right. It was a problem with firewall.
Unfortunately, I still have a problem. I was able to run desktop app, but still has same error. Can't find in docs the exact configuration for cypress.
For instance, there is a nice [guide](https://automate.browserstack.com/dashboard/v2/quick-start/get-started#run-sample-build) about selenium but not about cypress

**Comment by suryart** [comment]
@captain-yossarian : Did you face the same issue while re-trying? Can you please check the network? Look for any firewall rule or a proxy setting on your system. If it still fails despite having the right network. Try doing a curl on `https://api-cloud.browserstack.com` in verbose mode and check which step it is failing and provide us with that curl log in comments.

**Comment by captain-yossarian** [comment]
@suryart  thanks for your reply. It is working now. It was firewall isue and my stupidity )))
Feel free to close the issue
