### ISSUE TITLE
Cannot find module 'unzipper'

### ISSUE THREAD

**Issue by christemple** [browserstack/browserstack-cypress-cli#168]
I'm currently trying to upgrade from `1.8.1`, there's an issue with `1.9.0` whereby the CLI no longer waits for the browserstack build to finish (as if `--sync` isn't making a difference), so I thought I'd try bumping to `1.10.0`, however now I'm getting the following error:
```

[2021-10-01T11:56:56.660Z] Error: Cannot find module 'unzipper'

[2021-10-01T11:56:56.660Z] Require stack:

[2021-10-01T11:56:56.660Z] - /tmp/workspace/ata-webapp_test-pipeline-changes/node_modules/browserstack-cypress-cli/bin/helpers/buildArtifacts.js

[2021-10-01T11:56:56.660Z] - /tmp/workspace/ata-webapp_test-pipeline-changes/node_modules/browserstack-cypress-cli/bin/commands/runs.js

[2021-10-01T11:56:56.660Z] - /tmp/workspace/ata-webapp_test-pipeline-changes/node_modules/browserstack-cypress-cli/bin/runner.js

[2021-10-01T11:56:56.660Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[2021-10-01T11:56:56.660Z]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[2021-10-01T11:56:56.660Z]     at Module.require (internal/modules/cjs/loader.js:974:19)
[2021-10-01T11:56:56.660Z]     at require (internal/modules/cjs/helpers.js:93:18)
[2021-10-01T11:56:56.660Z]     at Object.<anonymous> (/tmp/workspace/ata-webapp_test-pipeline-changes/node_modules/browserstack-cypress-cli/bin/helpers/buildArtifacts.js:7:14)
[2021-10-01T11:56:56.660Z]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[2021-10-01T11:56:56.660Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[2021-10-01T11:56:56.660Z]     at Module.load (internal/modules/cjs/loader.js:950:32)
[2021-10-01T11:56:56.660Z]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[2021-10-01T11:56:56.660Z]     at Module.require (internal/modules/cjs/loader.js:974:19) {
[2021-10-01T11:56:56.660Z]   code: 'MODULE_NOT_FOUND',
[2021-10-01T11:56:56.660Z]   requireStack: [
[2021-10-01T11:56:56.660Z]     '/tmp/workspace/ata-webapp_test-pipeline-changes/node_modules/browserstack-cypress-cli/bin/helpers/buildArtifacts.js',
[2021-10-01T11:56:56.660Z]     '/tmp/workspace/ata-webapp_test-pipeline-changes/node_modules/browserstack-cypress-cli/bin/commands/runs.js',
[2021-10-01T11:56:56.660Z]     '/tmp/workspace/ata-webapp_test-pipeline-changes/node_modules/browserstack-cypress-cli/bin/runner.js'
[2021-10-01T11:56:56.660Z]   ]
[2021-10-01T11:56:56.660Z] }
[2021-10-01T11:56:56.660Z] error Command failed with exit code 1.
```

I had a quick look and seen that `unzipper` is only in the `devDependencies` of this NPM package, should it be a `dependency`?

**Comment by karanshah-browserstack** [comment]
@christemple Thanks for pointing this out, we are working on this and will release a patch soon.
