### ISSUE TITLE
Unable to retrieve local enviroment variable for npmrc

### ISSUE THREAD

**Issue by roydejager** [browserstack/browserstack-cypress-cli#178]
I have an npmrc file which contains an auth token stored within my .bash_profile.

When trying to run cypress through browserstack I get an error that this environment variable cannot be found. This package is also not included in the npm_dependencies, so after putting any hardcoded string in the npmrc file it will work. Is it possible to put in local environment variables or am I doing something wrong?

```json
 {
   "auth": {
     ...
   },
   "browsers": [
     {
       "browser": "chrome",
       "os": "Windows 10",
       "versions": [
         "latest"
       ]
     }
   ],
   "run_settings": {
     "cypress_config_file": "./cypress-dev.json",
     "project_name": "project",
     "build_name": "project build",
     "parallels": "1",
     "exclude": [],
     "npm_dependencies": {
       "typescript": "4.1.5"
     },
     "package_config_options": {},
     "headless": false,
     "sys_env_vars": ["FONTAWESOME_NPM_AUTH_TOKEN"]
   },
   "connection_settings": {
     "local": true,
     "local_identifier": null,
     "local_mode": null,
     "local_config_file": null
   },
   "disable_usage_reporting": true
 }
```

Npmrc:
```npmrc
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
```

Error when running on browserstack:
```
Error: Failed to replace env in config: ${FONTAWESOME_NPM_AUTH_TOKEN}
    at \cypress_node\node_modules\npm\lib\config\core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (\cypress_node\node_modules\npm\lib\config\core.js:411:12)
    at parseField (\cypress_node\node_modules\npm\lib\config\core.js:389:7)
    at \cypress_node\node_modules\npm\lib\config\core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (\cypress_node\node_modules\npm\lib\config\core.js:328:23)
    at ConfigChain.addString (\cypress_node\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (\cypress_node\node_modules\npm\lib\config\core.js:316:10)
    at \cypress_node\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:115:16
\cypress_node\node_modules\npm\lib\npm.js:59
      throw new Error('npm.load() required')
      ^
```

**Comment by Jaimin180296** [comment]
It seems that you are using sys_env_vars instead of system_env_vars, as a result, the env vars are not getting recognized. Follow this doc: https://www.browserstack.com/docs/automate/cypress/test-environment and also make the changes required changes in plugins/index.js as per this doc if not done.

**Comment by roydejager** [comment]
@Jaimin180296 I see that after changes sys into sytem it works now. Thank you very much.
